apiVersion: v1
kind: Service
metadata:
  name: devops-project-service
  labels:
    app: devops-project-app
spec:
  type: NodePort
  selector:
    app: devops-project-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
